// flow-typed signature: 12ecb3a0865e82aca614c4a382056fa1
// flow-typed version: <<STUB>>/esformatter-curly_v^0.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-curly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-curly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-curly/lib/hooks/import-declaration' {
  declare module.exports: any;
}

declare module 'esformatter-curly/lib/hooks/object-expression' {
  declare module.exports: any;
}

declare module 'esformatter-curly/lib/hooks/object-pattern' {
  declare module.exports: any;
}

declare module 'esformatter-curly/lib/index' {
  declare module.exports: any;
}

declare module 'esformatter-curly/lib/rc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-curly/lib/hooks/import-declaration.js' {
  declare module.exports: $Exports<'esformatter-curly/lib/hooks/import-declaration'>;
}
declare module 'esformatter-curly/lib/hooks/object-expression.js' {
  declare module.exports: $Exports<'esformatter-curly/lib/hooks/object-expression'>;
}
declare module 'esformatter-curly/lib/hooks/object-pattern.js' {
  declare module.exports: $Exports<'esformatter-curly/lib/hooks/object-pattern'>;
}
declare module 'esformatter-curly/lib/index.js' {
  declare module.exports: $Exports<'esformatter-curly/lib/index'>;
}
declare module 'esformatter-curly/lib/rc.js' {
  declare module.exports: $Exports<'esformatter-curly/lib/rc'>;
}
