// flow-typed signature: d1012cf0b870405168a9543faa88faee
// flow-typed version: <<STUB>>/rethink-migrate_v^1.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rethink-migrate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rethink-migrate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rethink-migrate/gulpfile' {
  declare module.exports: any;
}

declare module 'rethink-migrate/lib/create' {
  declare module.exports: any;
}

declare module 'rethink-migrate/lib/migrate' {
  declare module.exports: any;
}

declare module 'rethink-migrate/template' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/integration/helper' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/integration/rethinkdb.spec' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/integration/rethinkdbdash-nopool-cursor.spec' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/integration/rethinkdbdash-nopool-nocursor.spec' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/integration/rethinkdbdash-pool-cursor.spec' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/integration/rethinkdbdash-pool-nocursor.spec' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/migrations/20151005145709-create-table' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/migrations/20151005165432-insert-data' {
  declare module.exports: any;
}

declare module 'rethink-migrate/test/migrations/otherfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rethink-migrate/gulpfile.js' {
  declare module.exports: $Exports<'rethink-migrate/gulpfile'>;
}
declare module 'rethink-migrate/lib/create.js' {
  declare module.exports: $Exports<'rethink-migrate/lib/create'>;
}
declare module 'rethink-migrate/lib/migrate.js' {
  declare module.exports: $Exports<'rethink-migrate/lib/migrate'>;
}
declare module 'rethink-migrate/template.js' {
  declare module.exports: $Exports<'rethink-migrate/template'>;
}
declare module 'rethink-migrate/test/integration/helper.js' {
  declare module.exports: $Exports<'rethink-migrate/test/integration/helper'>;
}
declare module 'rethink-migrate/test/integration/rethinkdb.spec.js' {
  declare module.exports: $Exports<'rethink-migrate/test/integration/rethinkdb.spec'>;
}
declare module 'rethink-migrate/test/integration/rethinkdbdash-nopool-cursor.spec.js' {
  declare module.exports: $Exports<'rethink-migrate/test/integration/rethinkdbdash-nopool-cursor.spec'>;
}
declare module 'rethink-migrate/test/integration/rethinkdbdash-nopool-nocursor.spec.js' {
  declare module.exports: $Exports<'rethink-migrate/test/integration/rethinkdbdash-nopool-nocursor.spec'>;
}
declare module 'rethink-migrate/test/integration/rethinkdbdash-pool-cursor.spec.js' {
  declare module.exports: $Exports<'rethink-migrate/test/integration/rethinkdbdash-pool-cursor.spec'>;
}
declare module 'rethink-migrate/test/integration/rethinkdbdash-pool-nocursor.spec.js' {
  declare module.exports: $Exports<'rethink-migrate/test/integration/rethinkdbdash-pool-nocursor.spec'>;
}
declare module 'rethink-migrate/test/migrations/20151005145709-create-table.js' {
  declare module.exports: $Exports<'rethink-migrate/test/migrations/20151005145709-create-table'>;
}
declare module 'rethink-migrate/test/migrations/20151005165432-insert-data.js' {
  declare module.exports: $Exports<'rethink-migrate/test/migrations/20151005165432-insert-data'>;
}
declare module 'rethink-migrate/test/migrations/otherfile.js' {
  declare module.exports: $Exports<'rethink-migrate/test/migrations/otherfile'>;
}
